include: package:very_good_analysis/analysis_options.5.1.0.yaml
linter:
  rules:
    public_member_api_docs: false
    avoid_types_as_parameter_names: true
    prefer_single_quotes: true
    prefer_double_quotes: false
    prefer_const_constructors: true
    import_of_legacy_library_into_null_safe:
    lines_longer_than_80_chars : true



