name: flutter_ecogrow_customer
description: created by kon khmer
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: any
  cupertino_icons: ^1.0.8

  #state management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5

  #imag
  image_picker: ^1.0.7
  flutter_svg: ^2.0.10+1

  #local storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3

  #utils
  firebase_core: ^2.32.0


  #  firebase_analytics: ^10.9.0
  sizer: ^2.0.15
  dio: ^5.4.2+1

  flutter_secure_storage: ^9.0.0
  go_router: ^13.2.2
  fluttertoast: ^8.2.4
  loader_overlay: ^4.0.0
  loading_indicator: ^3.1.1

  #network
  http_client :
    path: package/http_client

  #local_service
  pinput: ^4.0.0
  cached_network_image: ^3.3.1
  firebase_auth: ^4.20.0
  firebase_crashlytics: ^3.5.7
  google_maps_flutter: ^2.3.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  permission_handler: ^11.0.0
  carousel_slider: ^4.2.1
  flutter_native_splash: ^2.3.0
  smooth_page_indicator: ^1.2.0+3
  logger: ^2.4.0
  animations: ^2.0.8
  animated_flip_counter: ^0.3.0
  flutter_lints: ^4.0.0
  skeletonizer: ^1.4.0
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  path_provider: ^2.1.4
  flutter_slidable: ^3.1.1


dev_dependencies:
#  flutter_test:
#    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
  bloc_test: ^9.1.7
  json_serializable: ^6.8.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

flutter_native_splash:
  # Background color of splash screen
  color: "#ffffff"
  # Image that you want to show
  image: assets/images/splash/logo.png
  # Splash Image to show in dark mode (Optional)
  image_dark: assets/images/splash/logo.png
  # Background color of dark mode (Optional)
  color_dark: "#000000"
  android: true
  ios: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/images/splash/
    - assets/svg/
    - assets/fonts/

  fonts:
    - family: Kantumruy Pro
      fonts:
        - asset: assets/fonts/kantumruy_pro/KantumruyPro-Thin.ttf
          weight: 100
        - asset: assets/fonts/kantumruy_pro/KantumruyPro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/kantumruy_pro/KantumruyPro-Light.ttf
          weight: 300
        - asset: assets/fonts/kantumruy_pro/KantumruyPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/kantumruy_pro/KantumruyPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/kantumruy_pro/KantumruyPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/kantumruy_pro/KantumruyPro-Bold.ttf
          weight: 700
