// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlWPVagTgmbUTB58jueuA6DoBpvKjlDYE',
    appId: '1:642357116011:web:258c418867f439ffa2052e',
    messagingSenderId: '642357116011',
    projectId: 'ecogrow-marketplace',
    authDomain: 'ecogrow-marketplace.firebaseapp.com',
    databaseURL: 'https://ecogrow-marketplace-default-rtdb.firebaseio.com',
    storageBucket: 'ecogrow-marketplace.appspot.com',
    measurementId: 'G-DCS0NHP41Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzIyRgm934hMeLrM6Myn-FDPApI6VlaKo',
    appId: '1:642357116011:android:c60cc51d83f7c2eba2052e',
    messagingSenderId: '642357116011',
    projectId: 'ecogrow-marketplace',
    databaseURL: 'https://ecogrow-marketplace-default-rtdb.firebaseio.com',
    storageBucket: 'ecogrow-marketplace.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeBygKTZwXKMrGUXIrJgQm5QCeZPwltu8',
    appId: '1:642357116011:ios:2729871fcca2fbb1a2052e',
    messagingSenderId: '642357116011',
    projectId: 'ecogrow-marketplace',
    databaseURL: 'https://ecogrow-marketplace-default-rtdb.firebaseio.com',
    storageBucket: 'ecogrow-marketplace.appspot.com',
    iosBundleId: 'kh.com.ecogrow.ecommerce.sale',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeBygKTZwXKMrGUXIrJgQm5QCeZPwltu8',
    appId: '1:642357116011:ios:6dfc66b0db739530a2052e',
    messagingSenderId: '642357116011',
    projectId: 'ecogrow-marketplace',
    databaseURL: 'https://ecogrow-marketplace-default-rtdb.firebaseio.com',
    storageBucket: 'ecogrow-marketplace.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlWPVagTgmbUTB58jueuA6DoBpvKjlDYE',
    appId: '1:642357116011:web:258c418867f439ffa2052e',
    messagingSenderId: '642357116011',
    projectId: 'ecogrow-marketplace',
    authDomain: 'ecogrow-marketplace.firebaseapp.com',
    databaseURL: 'https://ecogrow-marketplace-default-rtdb.firebaseio.com',
    storageBucket: 'ecogrow-marketplace.appspot.com',
    measurementId: 'G-DCS0NHP41Z',
  );
}
